version: '3'

services:
  nginx-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nginx-alias-traversal-image
    container_name: nginx-alias-traversal-container
    ports:
      - 80:8080 # localport:dockerport
